// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Project: htoochoon-l0l (package site.kargate.test.htoochoon).
/// ✅ ANDROID is fully configured with the real htoochoon-l0l credentials.
/// ⚠️ web / iOS / macOS / windows below still carry the OLD project
/// (182356452628 / htoochoon-13840) appId+apiKey, because those platform apps
/// were not registered in htoochoon-l0l (the provided google-services.json only
/// contained the Android client). If you ship those platforms, register them in
/// htoochoon-l0l and run:
///   flutterfire configure --project=htoochoon-l0l
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxDJBOEgr5pSTl9POAEwX4jNa-K6YMK10',
    appId: '1:182356452628:web:6ffb35141b2db37762ce01',
    messagingSenderId: '182356452628',
    projectId: 'htoochoon-l0l',
    authDomain: 'htoochoon-l0l.firebaseapp.com',
    storageBucket: 'htoochoon-l0l.firebasestorage.app',
    measurementId: 'G-Y76MM47WD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtOJnCmw-6cDPMvjpv2CVC7CRDksj6mwM',
    appId: '1:209273531390:android:910165ee3a10dbedd42eaf',
    messagingSenderId: '209273531390',
    projectId: 'htoochoon-l0l',
    storageBucket: 'htoochoon-l0l.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfTRFvRoPtFToUXrAshduMabyBvksgblw',
    appId: '1:182356452628:ios:da49206aa74d49e562ce01',
    messagingSenderId: '182356452628',
    projectId: 'htoochoon-l0l',
    storageBucket: 'htoochoon-l0l.firebasestorage.app',
    iosClientId: '182356452628-gcecqb6l1djghfm3ad4d8a0ftnq9d2tc.apps.googleusercontent.com',
    iosBundleId: 'com.example.htoochoonFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfTRFvRoPtFToUXrAshduMabyBvksgblw',
    appId: '1:182356452628:ios:da49206aa74d49e562ce01',
    messagingSenderId: '182356452628',
    projectId: 'htoochoon-l0l',
    storageBucket: 'htoochoon-l0l.firebasestorage.app',
    iosClientId: '182356452628-gcecqb6l1djghfm3ad4d8a0ftnq9d2tc.apps.googleusercontent.com',
    iosBundleId: 'com.example.htoochoonFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxDJBOEgr5pSTl9POAEwX4jNa-K6YMK10',
    appId: '1:182356452628:web:86a9c1dad499d21f62ce01',
    messagingSenderId: '182356452628',
    projectId: 'htoochoon-l0l',
    authDomain: 'htoochoon-l0l.firebaseapp.com',
    storageBucket: 'htoochoon-l0l.firebasestorage.app',
    measurementId: 'G-VDJTHND1T7',
  );

}